### ISSUE TITLE
MGT fiber offload issues.

### ISSUE THREAD

**Issue by zack-vii** [D-TACQ/AFHBA404#48]
After having trouble getting acq480 to work with rtm-t-stream I noticed that even for 425 the offload breaks after rebooting the carrier. this was not a problem before (~ a year ago). this might be related to my 480 issues. i will revert the AFHBA404 and see if i can find a version where it still works

**Comment by zack-vii** [comment]
might have been caused by a faulty insmod parameters: 
what parameters are required/recommended have impact on performance/functionality.
Is there a more detailed documentation about them other than
```
modinfo afhba.ko
```

**Comment by zack-vii** [comment]
works now.. seems like some options are bad for communication

aurora_monitor should be on .. 
I now have only 
afhba4_stream=4 afhba_nports=4 nbuffers=60 buffer_len=0x400000  assume_stuck_buffers_are_ok=1
and it works for 480 as well. a detailed documentation would be good..

**Comment by zack-vii** [comment]
no looks like thiese option must be given for it to work although the descriptions is written in a way that suggests this is the default. but it does not seem to be the case.

aurora_monitor=1 dma_descriptor_ram=1

**Comment by petermilne** [comment]
dma_descriptor_ram=1 has been default since:
40faf9c1 (Peter Milne    2018-07-05 08:06:17 +0100  105) int dma_descriptor_ram = 1;
It's definitely recommended for high throughput (lower bus access overhead).

aurora_monitor is still default disable in the driver, but has been enabled in ./scripts/loadNIRQ since
7cf07839 (dt100       2015-02-25 22:53:57 +0000  7) AMON=${AMON:-1}

It could be made default in the device driver, but there's also an ambition to make it interrupt driven.

afhba4_stream is a boolean. If you want to stream, set it.
